name: ticno_deta_recovery
description: A Flutter app for recovering deleted videos, audios, pictures, and documents.
version: 1.0.0+1

# Environment configuration for Flutter and Dart
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Core dependencies
  path_provider: ^2.0.15       # Access to file storage paths
  permission_handler: ^11.2.0 # Manage runtime permissions
  provider: ^6.1.5            # State management
  http: ^1.1.0                # To enable future API calls

dev_dependencies:
  flutter_test:
    sdk: flutter              # For unit and widget testing
  flutter_native_splash: ^2.3.0 # For splash screen generation
  flutter_launcher_icons: ^0.14.0 # For creating launcher icons

# Flutter configuration
flutter:
  uses-material-design: true

  # Assets declaration
  assets:
    - assets/icons/recover_icon.png
    - assets/icons/settings_icon.png
    - assets/images/splash_background.png
    - assets/images/app_logo.png

# Configuration for launcher icons
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"

# Configuration for splash screen
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash_background.png
  android: true
  ios: true
  
